name: among_us_helper
description: An app aimed at helping AmongUs players remember information during a session.
publish_to: 'none'

# The following defines the version and build number.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Packages are locked to a specific version to ensure stability across different dev environments.
  cupertino_icons: 1.0.0
  device_info:
  photo_view: 0.10.2
  flutter_reorderable_list: 0.1.5
  flutter_svg: 0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: AmongUsHelperApp
      fonts:
        - asset: assets/fonts/AmongUsHelperApp.ttf

  assets:
    - assets/players/brown.png
    - assets/players/red.png
    - assets/players/orange.png
    - assets/players/yellow.png
    - assets/players/lime.png
    - assets/players/green.png
    - assets/players/cyan.png
    - assets/players/blue.png
    - assets/players/purple.png
    - assets/players/pink.png
    - assets/players/white.png
    - assets/players/black.png

    # Figma source: https://www.figma.com/file/QWtEmeoN8KyW7VcOM3EGgI/AmongUs-Maps?node-id=0%3A1
    - assets/maps/mira.svg
    - assets/maps/skeld.svg
